### ISSUE TITLE
Search & Filtering issue with custom cell components 

### ISSUE THREAD

**Issue by akiarostami** [dasDaniel/svelte-table#54] opened 2021-10-29 03:39 UTC
I'm sorry that I have not created an example to show this error, but there is a render issue with search / filter + renderComponent. When rows get filtered, the view of the renderComponents don't get refreshed.

This is actually a known thing in Svelte. If #each blocks get changed, you should [use keyed blocks](https://svelte.dev/tutorial/keyed-each-blocks).

The fix is very easy, actually. All you have to do is add a key to your #each loop.

**Comment by dasDaniel** [comment] 2021-11-10 06:47
This is not an _error_, for performance reasons it's not ideal to re-render the component.
Can you provide an example why forcing a re-render would be necessary? I suspect more often than not, the re-render would be an unwanted feature.

**Comment by akiarostami** [comment] 2021-11-10 10:36
The problem is exactly what I explained. I am using several custom components via renderComponent, e.g. a component to show an Icon based on the value of a field. When I search/filter, those cells won't get updated, and it keeps showing the content of the pre-filter cells. This makes it impossible to use the search/filter feature and renderComponent in one table.

**Comment by dasDaniel** [comment] 2021-11-12 06:15
I might need an example. 

The behaviour I see is that the components reorder properly

[example repl](https://svelte.dev/repl/202f503021b94d0f98bad51854aa38fc)

can you provide an example?

**Comment by engintekin** [comment] 2022-03-04 04:11
hey @dasDaniel, thank you for this library. I'm probably using it very wrong but here's a [case](https://svelte.dev/repl/3a8ba72849e84643a93f4f14f982d116?version=3.46.4) that reproduces the issue for me. To reproduce it, you can click some of the checkboxes and then sort or filter the table.

In my app, I'm making an ajax call to server when user clicks on a checkbox and update row value with the server's response. But above repl is showing the same issue that I'm facing.

**Comment by dasDaniel** [comment] 2022-03-08 04:39
@engintekin thanks for the example. I see what you mean, and I will address it, but I cannot say when that'll be yet.

**Comment by dasDaniel** [comment] 2022-03-08 05:32
I had a look at the example and can see what's going on.

You're doing this inside the component

```js
const handleChange = (event) => {
  if(event.target.checked) {
    row.country = "Canada";			
  }
  else {
    row.country = "US";
  }
}
```

This is not going to work, because you're mutating the derived `row` data which does not update the source data. In order to trigger the reactivity, you need to mutate the `rows` passed to `<SvelteTable>`.

The documentation doesn't cover how to do that, but the way to achieve this is to pass a function to the component.

example:

Define a function that can override the rows

```js
let rows = generateData(5); // use let to allow overriding
function updateRow(id, key, value){
  rows = rows.map((r) => {
    if (r.id === id) r[key] = value;
    return r;
  })
}
```

and pass the function to the `renderComponent` prop
```js
{
  key: "inCa",
  title: "IN CANADA",
  value: v => v.country,
  renderComponent: {
    component: Status,
    props: {
      onChange: updateRow, 
    },
  },
```

then in the Status component you can call that function

```js
export let onChange;

const handleChange = () => {
  onChange(row.id, 'country', row.country === 'Canada' ? "US" : "Canada" )
}
```

Finally, it's also a good idea to key the entire component with the id

```html
{#key row.id}
	<label>
		<input type="checkbox" checked={row.country === "Canada"} on:change={handleChange}/>
		{row.country}
	</label>
{/key}
```

This is important if the interaction causes change in order. So if you are, for example, ordering by "In Canada" column, then if you were to click on the first checked input, two checked checkboxes would update and uncheck. This happens because the first click would would register a change in the rows which would change the order of the data. But because the `onChange` fires and updates the rows immediately, when the function finishes executing, the checkbox still updates, but now the checkbox is replaced by a different row's checkbox, so it would uncheck visually, but without the data update.

[repl](https://svelte.dev/repl/35a5b1180dd84374ac3df1420f776305?version=3.46.4)

**Comment by dasDaniel** [comment] 2022-03-08 05:35
@akiarostami in resolving, what I believe is an unrelated issue, I've come across an issue where the behaviour of the checkboxes required use of key blocks. Are you able to use the key blocks within the component to resolve the issue?

**Closed** 2022-12-03 14:54 UTC
